spring.application.name=U5W2D3
server.port=${PORT}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
CLOUDINARY_URL=cloudinary://${CLOUDINARY_APIKEY}:${CLOUDINARY_SECRET}@${CLOUDINARY_NAME}